=== openbmc/openpower-hw-diags/analyzer/ras-data/ras-data-schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "title": "RAS Data schema for openpower-hw-diags",
    "type": "object",
    "additionalProperties": false,
    "required": [ "model_ec", "version", "actions", "signatures" ],
    "properties": {
        "model_ec": {
            "type": "string",
            "pattern": "^[0-9A-Fa-f]{8}$"
        },
        "version": {
            "type": "integer",
            "minimum": 1
        },
        "units": {
            "type": "object",
            "additionalProperties": false,
            "patternProperties": {
                "^\\w+$": {
                    "type": "string",
                    "pattern": "^\\w+(\\/\\w+)*$"
                }
            }
        },
        "buses": {
            "type": "object",
            "additionalProperties": false,
            "patternProperties": {
                "^\\w+$": {
                    "type": "object",
                    "additionalProperties": false,
                    "required": [ "type" ],
                    "properties": {
                        "type": {
                            "type": "string",
                            "enum": [ "peer", "parent", "child" ]
                        },
                        "unit": {
                            "type": "string",
                            "pattern": "^\\w+$"
                        }
                    }
                }
            }
        },
        "actions": {
            "type": "object",
            "additionalProperties": false,
            "patternProperties": {
                "^\\w+$": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "additionalProperties": false,
                        "required": [ "type" ],
                        "properties": {
                            "type": {
                                "type": "string",
                                "enum": [
                                    "action",
                                    "callout_self",
                                    "callout_unit",
                                    "callout_connected",
                                    "callout_bus",
                                    "callout_clock",
                                    "callout_procedure",
                                    "callout_part",
                                    "plugin"
                                ]
                            },
                            "priority": {
                                "type": "string",
                                "enum": [
                                    "HIGH",
                                    "MED",
                                    "MED_A",
                                    "MED_B",
                                    "MED_C",
                                    "LOW"
                                ]
                            },
                            "guard": {
                                "type": "boolean"
                            },
                            "name": {
                                "type": "string",
                                "pattern": "^\\w+$"
                            },
                            "position": {
                                "type": "integer",
                                "minimum": 0,
                                "maximum": 1
                            }
                        },
                        "allOf": [
                            {
                                "if": {
                                    "properties": {
                                        "type": { "const": "action" }
                                    }
                                },
                                "then": {
                                    "required": [ "name" ],
                                    "not": { "required": [ "priority", "guard", "position" ] }
                                }
                            },
                            {
                                "if": {
                                    "properties": {
                                        "type": { "const": "callout_self" }
                                    }
                                },
                                "then": {
                                    "required": [ "priority", "guard" ],
                                    "not": { "required": [ "name", "position" ] }
                                }
                            },
                            {
                                "if": {
                                    "properties": {
                                        "type": { "const": "callout_unit" }
                                    }
                                },
                                "then": {
                                    "required": [ "name", "priority", "guard" ],
                                    "not": { "required": [ "position" ] }
                                }
                            },
                            {
                                "if": {
                                    "properties": {
                                        "type": { "const": "callout_connected" }
                                    }
                                },
                                "then": {
                                    "required": [ "name", "priority", "guard" ],
                                    "not": { "required": [ "position" ] }
                                }
                            },
                            {
                                "if": {
                                    "properties": {
                                        "type": { "const": "callout_bus" }
                                    }
                                },
                                "then": {
                                    "required": [ "name", "guard" ],
                                    "not": { "required": [ "priority", "position" ] }
                                }
                            },
                            {
                                "if": {
                                    "properties": {
                                        "type": { "const": "callout_clock" }
                                    }
                                },
                                "then": {
                                    "required": [ "priority", "guard", "position" ],
                                    "not": { "required": [ "name" ] }
                                }
                            },
                            {
                                "if": {
                                    "properties": {
                                        "type": { "const": "callout_procedure" }
                                    }
                                },
                                "then": {
                                    "required": [ "name", "priority" ],
                                    "not": { "required": [ "guard", "position" ] },
                                    "properties": {
                                        "name": {
                                            "enum": [
                                                "LEVEL2"
                                            ]
                                        }
                                    }
                                }
                            },
                            {
                                "if": {
                                    "properties": {
                                        "type": { "const": "callout_part" }
                                    }
                                },
                                "then": {
                                    "required": [ "name", "priority" ],
                                    "not": { "required": [ "guard", "position" ] },
                                    "properties": {
                                        "name": {
                                            "enum": []
                                        }
                                    }
                                }
                            },
                            {
                                "if": {
                                    "properties": {
                                        "type": { "const": "plugin" }
                                    }
                                },
                                "then": {
                                    "required": [ "name" ],
                                    "not": { "required": [ "priority", "guard", "position" ] }
                                }
                            }
                        ]
                    }
                }
            }
        },
        "signatures": {
            "type": "object",
            "additionalProperties": false,
            "patternProperties": {
                "^[0-9A-Fa-f]{4}$": {
                    "type": "object",
                    "additionalProperties": false,
                    "patternProperties": {
                        "^[0-9A-Fa-f]{2}$": {
                            "type": "object",
                            "additionalProperties": false,
                            "patternProperties": {
                                "^[0-9A-Fa-f]{2}$": {
                                    "type": "string",
                                    "pattern": "^\\w+$"
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}

=== openbmc/openpower-hw-diags/analyzer/ras-data/data/ras-data-explorer-11.json
{
    "model_ec": "60d20011",
    "version": 2,
    "units": {
        "mem_port": "mem_port0",
        "dimm": "mem_port0/dimm0"
    },
    "buses": {
        "omi_bus": {
            "type": "OMI_BUS"
        }
    },
    "actions": {
        "ocmb_M": [
            {
                "type": "callout_self",
                "priority": "MED",
                "guard": true
            }
        ],
        "level2_M": [
            {
                "type": "callout_procedure",
                "name": "LEVEL2",
                "priority": "MED"
            }
        ],
        "dimm_M": [
            {
                "type": "callout_unit",
                "name": "dimm",
                "priority": "MED",
                "guard": true
            }
        ],
        "mem_port_M": [
            {
                "type": "callout_unit",
                "name": "mem_port",
                "priority": "MED",
                "guard": true
            }
        ],
        "omi_M": [
            {
                "type": "callout_connected",
                "name": "omi_bus",
                "priority": "MED",
                "guard": true
            }
        ],
        "omi_bus": [
            {
                "type": "callout_self",
                "priority": "MED_A",
                "guard": true
            },
            {
                "type": "callout_connected",
                "name": "omi_bus",
                "priority": "MED_A",
                "guard": true
            },
            {
                "type": "callout_bus",
                "name": "omi_bus",
                "priority": "LOW",
                "guard": false
            }
        ],
        "ocmb_M_th1": [
            {
                "type": "action",
                "name": "ocmb_M"
            },
            {
                "type": "action",
                "name": "th_1"
            }
        ],
        "mem_port_M_th1": [
            {
                "type": "action",
                "name": "mem_port_M"
            },
            {
                "type": "action",
                "name": "th_1"
            }
        ],
        "dimm_M_th1": [
            {
                "type": "action",
                "name": "dimm_M"
            },
            {
                "type": "action",
                "name": "th_1"
            }
        ],
        "level2_M_th1": [
            {
                "type": "action",
                "name": "level2_M"
            },
            {
                "type": "action",
                "name": "th_1"
            }
        ],
        "omi_M_th1": [
            {
                "type": "action",
                "name": "omi_M"
            },
            {
                "type": "action",
                "name": "th_1"
            }
        ],
        "omi_bus_th1": [
            {
                "type": "action",
                "name": "omi_bus"
            },
            {
                "type": "action",
                "name": "th_1"
            }
        ],
        "level2_M_ocmb_L_th1": [
            {
                "type": "action",
                "name": "level2_M"
            },
            {
                "type": "callout_self",
                "priority": "LOW",
                "guard": false
            },
            {
                "type": "action",
                "name": "th_1"
            }
        ],
        "ocmb_H_omi_L_th1": [
            {
                "type": "callout_self",
                "priority": "HIGH",
                "guard": true
            },
            {
                "type": "callout_connected",
                "name": "omi_bus",
                "priority": "LOW",
                "guard": false
            },
            {
                "type": "action",
                "name": "th_1"
            }
        ],
        "dimm_H_mem_port_L_th1": [
            {
                "type": "callout_unit",
                "name": "dimm",
                "priority": "HIGH",
                "guard": true
            },
            {
                "type": "callout_unit",
                "name": "mem_port",
                "priority": "LOW",
                "guard": false
            },
            {
                "type": "action",
                "name": "th_1"
            }
        ],
        "dimm_H_mem_port_L_th_32perDay": [
            {
                "type": "callout_unit",
                "name": "dimm",
                "priority": "HIGH",
                "guard": true
            },
            {
                "type": "callout_unit",
                "name": "mem_port",
                "priority": "LOW",
                "guard": false
            },
            {
                "type": "action",
                "name": "th_32perDay"
            }
        ],
        "ocmb_M_th_32perDay": [
            {
                "type": "action",
                "name": "ocmb_M"
            },
            {
                "type": "action",
                "name": "th_32perDay"
            }
        ],
        "omi_M_th_32perDay": [
            {
                "type": "action",
                "name": "omi_M"
            },
            {
                "type": "action",
                "name": "th_32perDay"
            }
        ],
        "omi_bus_th_32perDay": [
            {
                "type": "action",
                "name": "omi_bus"
            },
            {
                "type": "action",
                "name": "th_32perDay"
            }
        ],
        "mem_port_M_th_32perDay": [
            {
                "type": "action",
                "name": "mem_port_M"
            },
            {
                "type": "action",
                "name": "th_32perDay"
            }
        ],
        "ocmb_M_info_only": [
            {
                "type": "action",
                "name": "ocmb_M_th_32perDay"
            },
            {
                "type": "flag",
                "name": "informational_only"
            }
        ],
        "omi_bus_info_only": [
            {
                "type": "action",
                "name": "omi_bus_th_32perDay"
            },
            {
                "type": "flag",
                "name": "informational_only"
            }
        ],
        "mem_port_M_info_only": [
            {
                "type": "action",
                "name": "mem_port_M_th_32perDay"
            },
            {
                "type": "flag",
                "name": "informational_only"
            }
        ],
        "downstream_attn": [
            {
                "type": "action",
                "name": "level2_M_th1"
            }
        ],
        "th_1": [],
        "th_32perDay": [
            {
                "type": "flag",
                "name": "recovered_error"
            }
        ],
        "mcbist_program_complete": [
            {
                "type": "action",
                "name": "level2_M_th1"
            }
        ],
        "omi_degraded_mode": [
            {
                "type": "action",
                "name": "omi_bus_th1"
            }
        ],
        "verify_chip_mark_0": [
            {
                "type": "action",
                "name": "dimm_M_th1"
            }
        ],
        "verify_chip_mark_1": [
            {
                "type": "action",
                "name": "dimm_M_th1"
            }
        ],
        "verify_chip_mark_2": [
            {
                "type": "action",
                "name": "dimm_M_th1"
            }
        ],
        "verify_chip_mark_3": [
            {
                "type": "action",
                "name": "dimm_M_th1"
            }
        ],
        "verify_chip_mark_4": [
            {
                "type": "action",
                "name": "dimm_M_th1"
            }
        ],
        "verify_chip_mark_5": [
            {
                "type": "action",
                "name": "dimm_M_th1"
            }
        ],
        "verify_chip_mark_6": [
            {
                "type": "action",
                "name": "dimm_M_th1"
            }
        ],
        "verify_chip_mark_7": [
            {
                "type": "action",
                "name": "dimm_M_th1"
            }
        ],
        "mainline_nce_tce_handling": [
            {
                "type": "action",
                "name": "dimm_M_th1"
            }
        ],
        "mainline_aue_iaue_handling": [
            {
                "type": "action",
                "name": "dimm_H_mem_port_L_th1"
            }
        ],
        "mainline_ue_handling": [
            {
                "type": "action",
                "name": "dimm_M_th1"
            }
        ],
        "mainline_iue_handling": [
            {
                "type": "action",
                "name": "dimm_M_th1"
            }
        ],
        "memory_impe_handling": [
            {
                "type": "action",
                "name": "dimm_M_th1"
            }
        ],
        "maintenance_aue_handling": [
            {
                "type": "action",
                "name": "dimm_H_mem_port_L_th1"
            }
        ],
        "maintenance_iue_handling": [
            {
                "type": "action",
                "name": "dimm_M_th1"
            }
        ]
    },
    "signatures": {
        "f6c2": {
            "00": {
                "00": "ocmb_M_info_only"
            },
            "01": {
                "00": "ocmb_M_th1",
                "flags": [
                    "sue_source"
                ]
            },
            "02": {
                "00": "omi_bus_th1",
                "flags": [
                    "sue_source"
                ]
            },
            "03": {
                "00": "omi_bus_th1",
                "flags": [
                    "sue_source"
                ]
            },
            "04": {
                "00": "omi_bus_th1",
                "flags": [
